### ISSUE TITLE
onde posso mudar o nome da conexão que aparece no celular 

### ISSUE THREAD

**Issue by rafaWPP** [w3nder/whaticket-free#1]
ao inves de apaecer Baileys no celular conectado mostra o nome definido 
exemplo
no whatsapp conectado
google Chrome(nome definido)

**Comment by w3nder** [comment]
https://github.com/w3nder/whaticket-free/blob/main/backend/src/libs/wbot.ts#L91

no makeWASocket({... browser: ["Nome Qualquer", "Chrome", "10.15.7"],
