### ISSUE TITLE
Fim do Baileys?

### ISSUE THREAD

**Issue by gigahertzinformatica** [w3nder/whaticket-free#2]
Bom dia amigo, o que vai acontecer a partir de agora que aparentemente o baileys fechou seu github. ainda será possível instalar ou pretende mudar para outra biblioteca.

**Comment by w3nder** [comment]
Bom dia, eu não irei manter esse projeto aqui atualizado ,e a Baileys vai ser continuado pelo os moderador do Discord. 

https://github.com/w3nder/whaticket-free/blob/main/backend/package.json#L20

**Comment by gigahertzinformatica** [comment]
Valeu W3nder por sua atenção e orientação. obg
