### ISSUE TITLE
npm run build erro.

### ISSUE THREAD

**Issue by Anderson-Nascimento-Mendonca** [w3nder/whaticket-free#3]
ao executar npm run build, terminal me retorna essas mensagem.
![image](https://user-images.githubusercontent.com/85626023/234375807-d2bad947-5311-4b73-a13e-3d4855953296.png)

**Comment by w3nder** [comment]
![image](https://user-images.githubusercontent.com/1123103/234444341-45164f5b-4faa-4910-9cc1-aa761baaca67.png)
