### ISSUE TITLE
Versão para MySQL?

### ISSUE THREAD

**Issue by Flag-King** [w3nder/whaticket-free#7]
Olá;
Existe uma versão deste projeto que utilize MySQL? É importante para minha integração com ERP atual.
Se não existir, há uma forma de adaptar?

Abraço!

**Comment by eldertheodoro** [comment]
Você já pensou em criar rotinas entre o PostGres e o MySQL para integrar ERP com o ChatBot?
Creio que oque irá subir de um para o outro seriam informações específicas.

Neste caso, poderiam haver triggers e rotinas específicas para a retroalimentação do sistema.

**Comment by Flag-King** [comment]
É uma boa possibilidade. Antes estou tentando esgotar as possibilidades desta versão da api utilizar nativamente o MySQL.
Valeu pela dica!

**Comment by allancmello** [comment]
Fala pessoal, blz!

Isso pode ser feito no backend, é só alterar/incluir  os dados no arquivo **dotenv ".env.example"** do banco desejado. 
Inclusive pode habilitar o acesso a múltiplos bancos de dados. 
Vcs podem **usar o Banco de dados que quiserem**, claro terão que instalar as libs referente ao mesmos, inclusive bancos NoSQL como o: MongoDB, Firebase, CouchDB, etc...

Na Doc do Sequelize e TypeOrm existem as instruções para realizar isso, use a força, leiam a documentação da Lib/ Driver de conexão usada para conectar ao Banco escolhido.
 
Segue exemplo de uma conexão para múltiplos BDs em **Postgres**.

![image](https://github.com/unkbot/whaticket-free/assets/1229105/1ec9f2d4-8481-4713-8125-0fc803ba7278)
