### ISSUE TITLE
Envio de mensagens por API dispara mensagem de ausência

### ISSUE THREAD

**Issue by adajaworski** [w3nder/whaticket-free#9]
Ao enviar mensagem por API a mensagem de ausência é disparada em seguida quando está no periodo de ausencia. Ideal seria que disparasse mensagem de ausência somente quando recebesse mensagem de contatos. Por gentileza considere a correção.

**Comment by allancmello** [comment]
Veja esse vídeo, ele explica como corrigir isso.

[https://www.youtube.com/watch?v=DBODColdH8s&lc=UgxuKjhuig8vZNK9oHR4AaABAg.9rpSftnwZ_G9rprwYgTFFu](url)
